name: ci

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: taehoio-global
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure gcloud docker
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            asia-northeast1-docker.pkg.dev/taehoio-global/docker-registry/youtube2notion:${{ github.sha }}

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Lint
        run: |
          make lint

  unittest:
    name: Unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Set up ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Test
        run: |
          make test
